apiVersion: v1
kind: Service
metadata:
  name: linkding
  namespace: linkding
spec:
  type: NodePort
  selector:
    app: linkding
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30090
